on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [0, 1, 2, 3]
    steps:
    - run: ip addr
      if: matrix.instance == 0
    - run: echo worker
      if: matrix.instance != 0
