on:
  push:
jobs:
  main:
    runs-on: macos-14
    steps:
    - run: |
        set -x
        brew install docker colima
        colima start || (cat /Users/runner/.colima/_lima/colima/ha.stderr.log && exit 1)
    - run: docker run --rm ubuntu:jammy bash -c 'echo hi'
  main2:
    runs-on: macos-13
    steps:
    - run: |
        brew install docker colima
        colima start
    - run: docker run --rm ubuntu:jammy bash -c 'echo hi'
