on:
  push:
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: fscarmen/warp-on-actions@v1.3
      - run: |
          set -x
          ip -6 addr show scope global 
          dig -t aaaa whoami.akamai.net
          dig whoami.akamai.net
