on:
  push:
jobs:
  main:
    runs-on: macos-14
    steps:
    - run: |
        brew install docker colima
        colima start
    - run: docker run --rm -ti ubuntu:jammy bash -c 'echo hi'
  main2:
    runs-on: macos-13
    steps:
    - run: |
        brew install docker colima
        colima start
    - run: docker run --rm -ti ubuntu:jammy bash -c 'echo hi'
